wrapperVersion=3.3.2
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
distributionSha256Sum=a555254316314a0f25c9e2b7d9ded268bec2e1f72e161dfc785e4423983b6b0e
